name: pentads-env
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - python=3.7
    - pip
    - git
    - cython
    - numpy
    - opencv
    - seaborn
    - pip:
        - cooler==0.8.11
        - cooltools==0.5.1
